title: Learning General Git Blog
author: CLIN  
email: Nickles255@sbcglobal.net
description: > # this means to ignore newlines until "baseurl:"
   Learning all about Git features avaiable in GITHUB.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
